name: Release

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "18.6.x"

      - name: Install dependencies
        run: npm install

      - name: Bump version and tag
        id: version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          release_branches: main

      # - name: Build for release
      #   run: npm run build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            black-list
            README.md
            LICENSE
          draft: true
          prerelease: true
          tag_name: ${{ steps.version.outputs.tag }}
          release_title: Release ${{ steps.version.outputs.tag }}
          body: |
            Release ${{ steps.version.outputs.tag }}
